// ============================================================
// English String Constants
// ============================================================
// All user-facing strings in English. Single source of truth.

export const EN = {
  // App
  appName: 'Kirsner Farm',
  appTagline: 'Fresh from the field to you',

  // Navigation Tabs
  nav: {
    home: 'Home',
    categories: 'Categories',
    cart: 'Cart',
    orders: 'Orders',
    account: 'Account',
    search: 'Search',
    favorites: 'Favorites',
  },

  // Home Screen
  home: {
    greeting: 'Hello',
    searchPlaceholder: 'Search products...',
    featuredProducts: 'Featured Products',
    categories: 'Categories',
    offers: 'Offers',
    seeAll: 'See All',
    newArrivals: 'New Arrivals',
    popularProducts: 'Best Sellers',
  },

  // Products
  product: {
    addToCart: 'Add to Cart',
    inCart: 'In Cart',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    price: 'Price',
    unit: 'Unit',
    quantity: 'Quantity',
    description: 'Description',
    relatedProducts: 'Related Products',
    organic: 'Organic',
    seasonal: 'Seasonal',
    featured: 'Featured',
    offer: 'Offer',
    perKg: 'per kg',
    perUnit: 'per unit',
    perPack: 'per pack',
    perLiter: 'per liter',
    filters: 'Filters',
    sortBy: 'Sort By',
    sortPrice: 'Price',
    sortPopular: 'Popular',
    sortNewest: 'Newest',
    filterCategory: 'Category',
    filterPrice: 'Price Range',
    filterInStock: 'In Stock Only',
    filterOrganic: 'Organic Only',
    filterSeasonal: 'Seasonal',
    noResults: 'No Results Found',
    tryDifferent: 'Try a different search',
  },

  // Cart
  cart: {
    title: 'Shopping Cart',
    empty: 'Cart is Empty',
    emptySubtitle: 'Add products to cart to continue',
    startShopping: 'Start Shopping',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    discount: 'Discount',
    total: 'Total',
    checkout: 'Checkout',
    remove: 'Remove',
    coupon: 'Coupon Code',
    applyCoupon: 'Apply',
    couponApplied: 'Coupon applied successfully',
    couponInvalid: 'Invalid coupon',
    freeDelivery: 'Free Delivery!',
    freeDeliveryFrom: 'Free delivery from ₪{amount}',
    itemsCount: '{count} items',
  },

  // Checkout
  checkout: {
    title: 'Checkout',
    selectAddress: 'Select Delivery Address',
    addAddress: 'Add Address',
    deliveryTime: 'Select Delivery Time',
    payment: 'Payment',
    review: 'Order Summary',
    placeOrder: 'Place Order',
    processing: 'Processing...',
    addressLabel: 'Address Name',
    street: 'Street',
    city: 'City',
    notes: 'Delivery Notes',
    timeSlots: {
      morning: 'Morning (08:00-12:00)',
      afternoon: 'Afternoon (12:00-16:00)',
      evening: 'Evening (16:00-20:00)',
    },
  },

  // Orders
  order: {
    title: 'My Orders',
    empty: 'No Orders Yet',
    emptySubtitle: 'Your orders will appear here',
    orderNumber: 'Order #',
    status: 'Status',
    date: 'Date',
    total: 'Total',
    items: 'Items',
    reorder: 'Reorder',
    trackDelivery: 'Track Delivery',
    details: 'Order Details',
    estimatedDelivery: 'Estimated Delivery',
    deliveryDriver: 'Driver',
    contactDriver: 'Contact Driver',
    statuses: {
      pending: 'Pending',
      confirmed: 'Confirmed',
      packing: 'Packing',
      out_for_delivery: 'Out for Delivery',
      delivered: 'Delivered',
      cancelled: 'Cancelled',
    },
    paymentStatuses: {
      pending: 'Payment Pending',
      paid: 'Paid',
      failed: 'Failed',
      refunded: 'Refunded',
    },
  },

  // Account
  account: {
    title: 'My Account',
    profile: 'Personal Details',
    addresses: 'Addresses',
    favorites: 'Favorite Products',
    orders: 'Order History',
    settings: 'Settings',
    darkMode: 'Dark Mode',
    support: 'Contact Support',
    signOut: 'Sign Out',
    signOutConfirm: 'Are you sure you want to sign out?',
    name: 'Full Name',
    phone: 'Phone',
    email: 'Email',
    save: 'Save',
    saved: 'Saved Successfully',
    adminPanel: 'Store Management',
  },

  // Auth
  auth: {
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    orContinueWith: 'Or continue with',
    fullName: 'Full Name',
    phone: 'Phone Number',
    resetSent: 'Password reset link sent',
    welcome: 'Welcome!',
    welcomeBack: 'Welcome Back!',
  },

  // Admin
  admin: {
    dashboard: 'Dashboard',
    products: 'Products',
    categories: 'Categories',
    orders: 'Orders',
    deliveries: 'Deliveries',
    banners: 'Banners',
    offers: 'Offers',
    users: 'Users',
    stats: {
      todayOrders: "Today's Orders",
      pendingDeliveries: 'Pending Deliveries',
      lowStock: 'Low Stock',
      topSelling: 'Top Selling',
      revenue: 'Revenue',
    },
    productForm: {
      add: 'Add Product',
      edit: 'Edit Product',
      name: 'Product Name',
      description: 'Description',
      price: 'Price',
      discountPrice: 'Discount Price',
      category: 'Category',
      unit: 'Unit of Measure',
      stock: 'Stock Quantity',
      image: 'Image',
      gallery: 'Gallery',
      featured: 'Featured Product',
      offer: 'Offer',
      active: 'Active',
      organic: 'Organic',
      seasonal: 'Seasonal Label',
      save: 'Save',
      delete: 'Delete',
      deleteConfirm: 'Are you sure you want to delete this product?',
    },
    orderActions: {
      confirm: 'Confirm Order',
      pack: 'Mark as Packed',
      ship: 'Ship Order',
      deliver: 'Mark as Delivered',
      cancel: 'Cancel Order',
    },
  },

  // Common
  common: {
    loading: 'Loading...',
    error: 'Error',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    shekel: '₪',
    search: 'Search',
    noData: 'No Data',
    pullToRefresh: 'Pull to Refresh',
    somethingWentWrong: 'Something Went Wrong',
  },
} as const;
