// ============================================================
// Hebrew String Constants
// ============================================================
// All user-facing strings in Hebrew. Single source of truth.

export const HE = {
  // App
  appName: 'משק קירשנר',
  appTagline: 'טרי מהשדה ישר אליך',

  // Navigation Tabs
  nav: {
    home: 'בית',
    categories: 'קטגוריות',
    cart: 'סל קניות',
    orders: 'הזמנות',
    account: 'חשבון',
    search: 'חיפוש',
    favorites: 'מועדפים',
  },

  // Home Screen
  home: {
    greeting: 'שלום',
    searchPlaceholder: 'חפש מוצרים...',
    featuredProducts: 'מוצרים מומלצים',
    categories: 'קטגוריות',
    offers: 'מבצעים',
    seeAll: 'הכל',
    newArrivals: 'חדש בחנות',
    popularProducts: 'הכי נמכרים',
  },

  // Products
  product: {
    addToCart: 'הוסף לסל',
    inCart: 'בסל',
    outOfStock: 'אזל מהמלאי',
    inStock: 'במלאי',
    lowStock: 'מלאי נמוך',
    price: 'מחיר',
    unit: 'יחידה',
    quantity: 'כמות',
    description: 'תיאור',
    relatedProducts: 'מוצרים דומים',
    organic: 'אורגני',
    seasonal: 'עונתי',
    featured: 'מומלץ',
    offer: 'מבצע',
    perKg: 'ל-ק"ג',
    perUnit: 'ליחידה',
    perPack: 'לחבילה',
    perLiter: 'לליטר',
    filters: 'סינון',
    sortBy: 'מיון לפי',
    sortPrice: 'מחיר',
    sortPopular: 'פופולריות',
    sortNewest: 'חדש',
    filterCategory: 'קטגוריה',
    filterPrice: 'טווח מחירים',
    filterInStock: 'במלאי בלבד',
    filterOrganic: 'אורגני בלבד',
    filterSeasonal: 'עונתי',
    noResults: 'לא נמצאו תוצאות',
    tryDifferent: 'נסו לחפש מילה אחרת',
  },

  // Cart
  cart: {
    title: 'סל קניות',
    empty: 'הסל ריק',
    emptySubtitle: 'הוסיפו מוצרים לסל כדי להמשיך',
    startShopping: 'התחילו לקנות',
    subtotal: 'סה"כ ביניים',
    deliveryFee: 'דמי משלוח',
    discount: 'הנחה',
    total: 'סה"כ לתשלום',
    checkout: 'לתשלום',
    remove: 'הסר',
    coupon: 'קוד קופון',
    applyCoupon: 'החל',
    couponApplied: 'קופון הוחל בהצלחה',
    couponInvalid: 'קופון לא תקף',
    freeDelivery: 'משלוח חינם!',
    freeDeliveryFrom: 'משלוח חינם מ-₪{amount}',
    itemsCount: '{count} פריטים',
  },

  // Checkout
  checkout: {
    title: 'תשלום',
    selectAddress: 'בחר כתובת למשלוח',
    addAddress: 'הוסף כתובת',
    deliveryTime: 'בחר זמן משלוח',
    payment: 'תשלום',
    review: 'סיכום הזמנה',
    placeOrder: 'אשר הזמנה',
    processing: 'מעבד...',
    addressLabel: 'שם הכתובת',
    street: 'רחוב',
    city: 'עיר',
    notes: 'הערות למשלוח',
    timeSlots: {
      morning: 'בוקר (08:00-12:00)',
      afternoon: 'צהריים (12:00-16:00)',
      evening: 'ערב (16:00-20:00)',
    },
  },

  // Orders
  order: {
    title: 'ההזמנות שלי',
    empty: 'אין הזמנות עדיין',
    emptySubtitle: 'ההזמנות שלכם יופיעו כאן',
    orderNumber: 'הזמנה מס\'',
    status: 'סטטוס',
    date: 'תאריך',
    total: 'סה"כ',
    items: 'פריטים',
    reorder: 'הזמן שוב',
    trackDelivery: 'עקוב אחר משלוח',
    details: 'פרטי הזמנה',
    estimatedDelivery: 'זמן משלוח משוער',
    deliveryDriver: 'שליח',
    contactDriver: 'צור קשר עם השליח',
    statuses: {
      pending: 'ממתינה לאישור',
      confirmed: 'אושרה',
      packing: 'נארזת',
      out_for_delivery: 'בדרך אליך',
      delivered: 'נמסרה',
      cancelled: 'בוטלה',
    },
    paymentStatuses: {
      pending: 'ממתין לתשלום',
      paid: 'שולם',
      failed: 'נכשל',
      refunded: 'הוחזר',
    },
  },

  // Account
  account: {
    title: 'החשבון שלי',
    profile: 'פרטים אישיים',
    addresses: 'כתובות',
    favorites: 'מוצרים מועדפים',
    orders: 'היסטוריית הזמנות',
    settings: 'הגדרות',
    darkMode: 'מצב כהה',
    support: 'צור קשר',
    signOut: 'התנתק',
    signOutConfirm: 'בטוח שברצונך להתנתק?',
    name: 'שם מלא',
    phone: 'טלפון',
    email: 'אימייל',
    save: 'שמור',
    saved: 'נשמר בהצלחה',
    adminPanel: 'ניהול החנות',
  },

  // Auth
  auth: {
    login: 'התחברות',
    register: 'הרשמה',
    email: 'אימייל',
    password: 'סיסמה',
    confirmPassword: 'אימות סיסמה',
    forgotPassword: 'שכחתי סיסמה',
    resetPassword: 'איפוס סיסמה',
    noAccount: 'אין לך חשבון?',
    hasAccount: 'כבר יש לך חשבון?',
    signUp: 'הירשם',
    signIn: 'התחבר',
    orContinueWith: 'או המשך עם',
    fullName: 'שם מלא',
    phone: 'מספר טלפון',
    resetSent: 'נשלח קישור לאיפוס סיסמה',
    welcome: 'ברוכים הבאים!',
    welcomeBack: 'שמחים לראותך שוב!',
  },

  // Admin
  admin: {
    dashboard: 'לוח בקרה',
    products: 'מוצרים',
    categories: 'קטגוריות',
    orders: 'הזמנות',
    deliveries: 'משלוחים',
    banners: 'באנרים',
    offers: 'מבצעים',
    users: 'משתמשים',
    stats: {
      todayOrders: 'הזמנות היום',
      pendingDeliveries: 'משלוחים ממתינים',
      lowStock: 'מלאי נמוך',
      topSelling: 'הכי נמכרים',
      revenue: 'הכנסות',
    },
    productForm: {
      add: 'הוסף מוצר',
      edit: 'ערוך מוצר',
      name: 'שם המוצר',
      description: 'תיאור',
      price: 'מחיר',
      discountPrice: 'מחיר מבצע',
      category: 'קטגוריה',
      unit: 'יחידת מידה',
      stock: 'כמות במלאי',
      image: 'תמונה',
      gallery: 'גלריה',
      featured: 'מוצר מומלץ',
      offer: 'מבצע',
      active: 'פעיל',
      organic: 'אורגני',
      seasonal: 'תווית עונתית',
      save: 'שמור',
      delete: 'מחק',
      deleteConfirm: 'בטוח שברצונך למחוק מוצר זה?',
    },
    orderActions: {
      confirm: 'אשר הזמנה',
      pack: 'סמן כנארזת',
      ship: 'יצא למשלוח',
      deliver: 'סמן כנמסרה',
      cancel: 'בטל הזמנה',
    },
  },

  // Common
  common: {
    loading: 'טוען...',
    error: 'שגיאה',
    retry: 'נסה שנית',
    cancel: 'ביטול',
    confirm: 'אישור',
    save: 'שמור',
    delete: 'מחק',
    edit: 'ערוך',
    add: 'הוסף',
    back: 'חזור',
    next: 'הבא',
    done: 'סיום',
    close: 'סגור',
    yes: 'כן',
    no: 'לא',
    ok: 'אישור',
    shekel: '₪',
    search: 'חיפוש',
    noData: 'אין נתונים',
    pullToRefresh: 'משוך לרענון',
    somethingWentWrong: 'משהו השתבש',
  },
} as const;
